### ISSUE TITLE
admin vs non-admin

### ISSUE THREAD

**Issue by eoliveros** [djpnewton/zap_app#1]
I have two accounts:
e.f.oliveros@gmail.com - zap merchant (admin)
eocrypto00@gmail.com - zap merchant(non-admin)

e.f.oliveros@gmail.com - 1 admin api key
eocrypto00@gmail.com - 1 admin api key
                                        - 1 non-admin api key

scanning eocrypto00 non-admin api key, I see I have "Receive Zap" button. --- successful result
scanning eocrypto admin api-key, i could only see the "Receive Zap" button. Shouldn't I be able to see the "Send button" and the Scan?

Tried scanning the api-key for e.f.oliveros and its not showing the "Send button" and scan as well.

**Comment by djpnewton** [comment]
You only will have a send button if you generate (or recover) a wallet seed

**Comment by eoliveros** [comment]
So no real difference between scanning the QR code between admin  and non-admin api-key?


Erick

**Comment by djpnewton** [comment]
When you scan an admin api key it allows you to set the account wallet address on the portal.

This means then when other lite mode wallets scan an api key they can get the wallet address

**Comment by eoliveros** [comment]
cool. so i need to recover the wallet via seed and then set the api key (admin) to get the send zap and scan qr code. so the initial step would be to restore the seed.
