### ISSUE TITLE
merchant wallet issue

### ISSUE THREAD

**Issue by eoliveros** [djpnewton/zap_app#2]
When trying to be a slave ie. POS without "recovery word" by selecting "Scan merchant api key".
After scanning, it would loop over the recovery words screen.

**Comment by eoliveros** [comment]
steps to reproduce the problem:

1. Deleted the app.
2 . Reinstall the app.
3. Got a message on the screen “You do not have recovery words or an address saved, what would you like to do?” > “Scan merchant api key”
4. Enable the camera
5. Screen loops back to “You do not have recovery words or an address saved, what would you like to do?” and there’s a sliding pop up window at the bottom saying “No wallet address?” or something. Only shows up for 1  second.

**Comment by djpnewton** [comment]
I think this is fixed

**Comment by eoliveros** [comment]
I just checked this on the Heroku. For some reason there’s a wallet “None” which if selected, instead of showing all the transactions with no wallet address in it, its not showing any transactions at all.

I think its searching a device_name = “None” rather than None.


Erick
