### ISSUE TITLE
Zap Merchant App 1.2.10 - No QR code created in Receive Zap

### ISSUE THREAD

**Issue by Amyredrat19** [djpnewton/zap_app#29]
In the latest version 1.2.10, when click on receive Zap, the QR code does not display

**Comment by djpnewton** [comment]
It starts out in NZD mode so if you do not have a API KEY set up it can not do the conversion

**Comment by djpnewton** [comment]
fix: show qr code when in zap mode even if now API KEY present in 7f0f5729
