### ISSUE TITLE
Zap Merchant App - Pop up for notification

### ISSUE THREAD

**Issue by Amyredrat19** [djpnewton/zap_app#3]
Notification for payment was not consistent.  the notification pop up on the first payment but not the rest of the payments

**Comment by djpnewton** [comment]
I think this is fixed in the new version (1.2.4)

**Comment by Amyredrat19** [comment]
2nd  notification come thru

**Comment by Amyredrat19** [comment]
When did further testing, the notification stopped working

**Comment by djpnewton** [comment]
hmm,  I cant seem to reproduce the problem

**Comment by Amyredrat19** [comment]
We have 1 or 2 notifications and after that, we don't get the notification if we receive any more fund.

**Comment by djpnewton** [comment]
I noticed this in the demo yesterday.

I think it might happen when the application goes to the background (maybe the websocket dies in that situation). Then when the app is brought to focus again the notifications websocket is not responsive

There is probably an event (app focus or something) that I can try and reinit the notifications websocket

It may be possible that this effects iOS and not Android

**Comment by djpnewton** [comment]
I have been able to reproduce the issue but only on iOS so far

**Comment by djpnewton** [comment]
We might be able to use WidgetsBindingObserver (https://www.reddit.com/r/FlutterDev/comments/brecrg/how_to_know_when_app_goes_to_backgroundforeground/) to detect when the app goes into the background/foreground and so to try and revive the socket

**Comment by Amyredrat19** [comment]
@Dan, did you want me to try something here?  Not sure what you want me to do?

**Comment by djpnewton** [comment]
no its fine, if I need anything from you I will reassign the issue to you

**Comment by djpnewton** [comment]
should be fixed in da2fbad
