### ISSUE TITLE
Version 1.2.10 under transaction, the NZD is not displaying

### ISSUE THREAD

**Issue by Amyredrat19** [djpnewton/zap_app#30]
In the transaction, the screen is no longer displaying the NZD, only showing the Zap value

**Comment by djpnewton** [comment]
Is this the tx notification or the historical transactions list page?

**Comment by Amyredrat19** [comment]
Yes it is

**Comment by Amyredrat19** [comment]
Can we also highlight or bold the writing of internet banking login & password, please?

 
You have requested to add some information on the BUY Zap page re Account2Account.  I have gathered some information on Account2Account, is that what you are looking for:
 
Account2Account
	The Account2Account page is securely hosted by Windcave (a Level 1 service provider) and is compliant to PCI DSS. 
	Abiding by the comprehensive set of requirements of PCI DSS means that Windcave uses the latest security technologies to ensure the safe handling of all sensitive data.  
	During the course of the Account2Account payment process, Windcave does not store any of the customer's bank account information. The same security features setup on the customer's bank account, such as additional authentication methods, are prompted during the course of the Account2Account payment process. 
	Supported Banks in New Zealand 
o	ANZ
o	ASB
o	BNZ
o	Kiwibank
o	The Co-operative Bank
o	TSB
o	Westpac

**Comment by djpnewton** [comment]
> Can we also highlight or bold the writing of internet banking login & password, please?
> 
> You have requested to add some information on the BUY Zap page re Account2Account. I have gathered some information on Account2Account, is that what you are looking for:
> 
> Account2Account
>  The Account2Account page is securely hosted by Windcave (a Level 1 service provider) and is compliant to PCI DSS.
>  Abiding by the comprehensive set of requirements of PCI DSS means that Windcave uses the latest security technologies to ensure the safe handling of all sensitive data.
>  During the course of the Account2Account payment process, Windcave does not store any of the customer's bank account information. The same security features setup on the customer's bank account, such as additional authentication methods, are prompted during the course of the Account2Account payment process.
>  Supported Banks in New Zealand
> o ANZ
> o ASB
> o BNZ
> o Kiwibank
> o The Co-operative Bank
> o TSB
> o Westpac

copied info to: https://github.com/zap-me/zap-bronze/issues/24

**Comment by djpnewton** [comment]
to show NZD values you need to have a merchant portal api key
