### ISSUE TITLE
Zap Merchant App - Date

### ISSUE THREAD

**Issue by Amyredrat19** [djpnewton/zap_app#6]
Merchant Transaction Date on the Portal is a US  date, can we change this?

**Comment by djpnewton** [comment]
done

**Comment by Amyredrat19** [comment]
Will that change the existing transaction date or just the new one?

![image](https://user-images.githubusercontent.com/64056604/82286200-47dc2800-99f1-11ea-9e81-0c7e2ae66166.png)
