### ISSUE TITLE
Zap Merchant App - sending to the same wallet

### ISSUE THREAD

**Issue by Amyredrat19** [djpnewton/zap_app#7]
We have an Admin wallet scanning a Secondary Wallet QR code and in the Portal transaction, it only shows the Out transactions.  Shouldn't the amount go back to the Admin wallet?

Txid:  Epvt4vk6jZH2XwUuyqHkwWBdw7xEazZ6ebGn5FZ6T1WS

**Comment by djpnewton** [comment]
it shows as out because the sender and recipient are the same, therefore the account balance is reduced by the transaction fee
