### ISSUE TITLE
Zap Merchant App - Transaction not showing on the merchant portal for the sender

### ISSUE THREAD

**Issue by Amyredrat19** [djpnewton/zap_app#8]
Using the merchant wallet (both Kevin and Amy) has scanned a QR code from Kirsty Admin Wallet.  the payment goes out and showing on the phone wallet for Kevin and Amy, but not on the Portal for Kevin or Amy.

Kirsty's Admin Txid:
Payment from Amy: 4mxHQEg3PzKTqNxJ7dHnqjVNPv9AmwR1LxWE1LT9vgur
Payment from Kevin: H9e7ja53op5k7dhz6a5UM9rEuFR56joJbNKgvo2BLNpA

**Comment by djpnewton** [comment]
on the merchant tx view of the merchant portal there is an "update" button, after pressing that do the txs show up?

**Comment by Amyredrat19** [comment]
Yes that works when I click update - CLOSED
