### ISSUE TITLE
Zap Merchant App - Receive Zap

### ISSUE THREAD

**Issue by Amyredrat19** [djpnewton/zap_app#9]
When we create a QR code in the Receive Zap function, can we add a button "Create QR code" when clicked on it, takes the number pad out to display the full QR code?

**Comment by djpnewton** [comment]
i am not sure i understand, when you click the amount field a number pad is shown to enter the amount

**Comment by Amyredrat19** [comment]
At the moment, when we enter the amount on the Received Zap page, the pin pad does not go away.
Can we change it so that after entering the amount we can get rid of the pin pad?

**Comment by djpnewton** [comment]
how do we tell that they have finished?

on android the pin pad has a 'done' button but iOS does not

**Comment by Amyredrat19** [comment]
Do we make that two steps like the Zap app, where you type in the Zap amount with a Create QR button, then create the QR code and have the Done button?

**Comment by djpnewton** [comment]
There are two issues I see on iOS

1. the number pad does not allow for the decimal point
2. there is no way to get rid of the number pad (android numpad has a down arrow to close the numpad)

**Comment by djpnewton** [comment]
fixed in commit e0c68c9
